### ISSUE TITLE
@fewcha/web3 - Cannot use import statement outside a module

### ISSUE THREAD

**Issue by topazso** [hippospace/aptos-wallet-adapter#1]
`fewcha/aptos/dist/api/http-client.js`

This is broken with NextJS. Is the fewcha sdk a required dependency?

**Comment by pierreneter** [comment]
@topazso this issue from Fewcha's lib, not issue of hippo, I'm fixing it

**Comment by tom-hippo** [comment]
This will be closed for now. Feel free to reopen it if the issue persists.
