### ISSUE TITLE
No max gas parameter for martian wallet

### ISSUE THREAD

**Issue by topazso** [hippospace/aptos-wallet-adapter#27]

**Comment by topazso** [comment]
https://github.com/hippospace/aptos-wallet-adapter/blob/4f08430838992d8c8fe6f06bc5edb98256fe13d9/packages/aptos-wallet-adapter/src/WalletAdapters/MartianWallet.ts#L37

**Comment by tom-hippo** [comment]
it is supported in the latest version
https://github.com/hippospace/aptos-wallet-adapter/blob/ceb69d0dec161f14794c2aeb89f777ea4b32e1ea/packages/aptos-wallet-adapter/src/WalletProviders/useWallet.ts#L26-L29
