### ISSUE TITLE
WalletNotSelectedError after installing v1.3.7

### ISSUE THREAD

**Issue by chungquantin** [hippospace/aptos-wallet-adapter#28]
I got this error after installing v1.3.7 and I can't connect to a a wallet
![Screen Shot 2022-09-15 at 09 09 23](https://user-images.githubusercontent.com/56880684/190296659-48fd6eed-1972-44a7-b20a-419fab096150.png)

**Comment by pisomanik** [comment]
You need to use `select(<WALLET_NAME>)` then use the `connect(<WALLET_NAME>)` to connect to the wallet.

```ts
 onClick={() => {
          select(option.name); // ADD THIS LINE  
          connect(option.name);
          }}
```

**Comment by chungquantin** [comment]
Thank you for your response @pisomanik. I tried and now it connects but does not ask the wallet to approve and publicKey of wallet is not shown. You can see the log below
![Screen Shot 2022-09-15 at 17 36 52](https://user-images.githubusercontent.com/56880684/190382924-ebeb91e7-e2d2-41bb-aa10-64cdc09a765d.png)

**Comment by chungquantin** [comment]
Adding `autoConnect` attribute to the WalletProvider seems solve the issue
