### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by GetWebHB** [hippospace/aptos-wallet-adapter#35]
![image](https://user-images.githubusercontent.com/49827327/191645872-fcaac277-b820-46f5-a37b-bb4a8e89f033.png)
![image](https://user-images.githubusercontent.com/49827327/191646055-aa609183-6962-4713-b2c8-506a19b42358.png)

**Comment by tom-hippo** [comment]
Please check out the latest develop doc in: https://github.com/hippospace/aptos-wallet-adapter/tree/main/packages/aptos-wallet-adapter#use-react-provider
