### ISSUE TITLE
connection failed

### ISSUE THREAD

**Issue by GetWebHB** [hippospace/aptos-wallet-adapter#36]
![1663814961375](https://user-images.githubusercontent.com/49827327/191647356-b2153cf6-b377-4ee8-9375-ee2ca0a4115d.jpg)
![image](https://user-images.githubusercontent.com/49827327/191647710-d5f7d7a5-31a2-40e5-9737-a8e64c6a11b3.png)

**Comment by tom-konomi** [comment]
We have updated the connection method in order to support Auto connect. Please checkout the latest doc in https://github.com/hippospace/aptos-wallet-adapter/tree/main/packages/aptos-wallet-adapter#use-react-provider

**Comment by tom-hippo** [comment]
We have updated the connection method in order to support Auto connect. Please checkout the latest doc in https://github.com/hippospace/aptos-wallet-adapter/tree/main/packages/aptos-wallet-adapter#use-react-provider
