### ISSUE TITLE
[Bug] Require update Aptos SDK to v1.3.7 and catch up with the latest devnet release

### ISSUE THREAD

**Issue by chungquantin** [hippospace/aptos-wallet-adapter#6]
## Issue
I have an app running on devnet. After the Aptos devnet release today and the aptos sdk is updated to `v1.3.7`. Seems like there's a bug with the aptos-wallet-adapter. I checked the aptos-wallet-adapter and seems like it still use `v1.3.6`. 
Seems like this method breaks due to the recent update https://github.com/hippospace/aptos-wallet-adapter/blob/main/packages/aptos-wallet-adapter/src/utilities/util.ts
## Expected behavior
- Replace `script_function_payload` to `entry_function_payload`
- Update Aptos SDK to v1.3.7

**Comment by tom-hippo** [comment]
Hi, our team strikes our best to keep up with the rapid changing environment of Aptos and wallets. Thank you for the report!
