### ISSUE TITLE
clean up deps and correctly specify dev/peer deps

### ISSUE THREAD

**Issue by zhelezkov** [hippospace/aptos-wallet-adapter#60]
Hey,

First of all thanks for taking a lift and making a great abstraction on top of other wallets!

Just wanna to propose a small improvement, is to correctly distribute deps to peer and dev one.
For example, you have `@types/*`(https://github.com/hippospace/aptos-wallet-adapter/blob/main/packages/aptos-wallet-adapter/package.json#L30) deps and `dependencies`, but it should be in `devDependencies`, otherwise it might lead to the types conflicts, especially for the projects that uses react^17.

And the second one is to move aptos to peer dependency(https://github.com/hippospace/aptos-wallet-adapter/blob/main/packages/aptos-wallet-adapter/package.json#L32), since the host app should force the version.

As a reference please check how deps well structured in solana wallet adapter: https://github.com/solana-labs/wallet-adapter/blob/master/packages/core/base/package.json

Thanks!

**Comment by tom-hippo** [comment]
Thank you for the suggestion. It is updated in the latest commit: https://github.com/hippospace/aptos-wallet-adapter/commit/b768aad73d265105b4c83eb9623240ab3528ff4b
